var data = [
  {
    id: "100",
    name: "J Phone 5",
    shortDesc: "red color with 15 mp camera",
    img: "100.png",
    price: 1000,
    averageRating: 4,
    noOfpeopleRated: 40,
  },
  {
    id: "101",
    name: "J Phone 6",
    shortDesc: "green color with 10 mp camera",
    img: "101.png",
    price: 900,
    averageRating: 4.5,
    noOfpeopleRated: 91,
  },
  {
    id: "102",
    name: "J Phone 7",
    shortDesc: "blue color with 8 mp camera",
    img: "102.png",
    price: 600,
    averageRating: 4.1,
    noOfpeopleRated: 84,
  },
  {
    id: "103",
    name: "J Phone 8",
    shortDesc: "black color with 12 mp camera",
    img: "103.png",
    price: 1000,
    averageRating: 3.4,
    noOfpeopleRated: 45,
  },
  {
    id: "104",
    name: "J Phone 9",
    shortDesc: "white color with 20 mp camera",
    img: "104.png",
    price: 1300,
    averageRating: 2,
    noOfpeopleRated: 78,
  },
];
